services:
  consumer:
    build:
      context: .
      dockerfile: apps/consumer/dockerfile
    container_name: grpc-consumer
    restart: unless-stopped
    networks:
      - grpc-net

  producer:
    build:
      context: .
      dockerfile: apps/producer/dockerfile
    container_name: grpc-producer
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:${PORT}"
    depends_on:
      - consumer
    networks:
      - grpc-net

networks:
  grpc-net:
    driver: bridge
