services:
  consumer:
    image: ghcr.io/danilshk/test-grpc-consumer:latest
    container_name: grpc-consumer
    restart: unless-stopped
    networks:
      - grpc-net

  producer:
    image: ghcr.io/danilshk/test-grpc-producer:latest
    container_name: grpc-producer
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - consumer
    networks:
      - grpc-net

networks:
  grpc-net:
    driver: bridge
