// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               v5.29.3
// source: libs/proto/src/users/users.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "users";

/** hero/hero.proto */

export interface UserFilter {
  id: number;
  name: string;
  age: number;
}

export interface GetFilteredUsersRequest {
  users: UserFilter[];
}

export interface Empty {
}

export const USERS_PACKAGE_NAME = "users";

export interface UsersServiceClient {
  getFilteredUsers(request: GetFilteredUsersRequest): Observable<Empty>;
}

export interface UsersServiceController {
  getFilteredUsers(request: GetFilteredUsersRequest): Promise<Empty> | Observable<Empty> | Empty;
}

export function UsersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getFilteredUsers"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USERS_SERVICE_NAME = "UsersService";
